spring:
  application:
    name: kotlin-reladomo-sample
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

reladomo:
  kotlin:
    connection-manager-config-file: reladomo-runtime-config.xml
    default-transaction-timeout: 120
    default-business-date-provider: CURRENT_TIMESTAMP
    default-processing-date-provider: CURRENT_TIMESTAMP

logging:
  level:
    io.github.kotlinreladomo: DEBUG
    com.gs.fw.common.mithra: INFO
    org.springframework.jdbc: DEBUG